version: "3.8"
services:
  monitor:
    build: .
    ports:
      - "9090:9090" # Expose monitor's metrics port
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090" # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Grafana UI
    depends_on:
      - prometheus
